version: "3.4"
services:

        jekyll:
                image: jekyll/jekyll:pages
                ports:
                        - "4000:4000"
                volumes:
                        - ".:/srv/jekyll"
                container_name: "jekyll_github"
                working_dir: "/srv/jekyll"
                entrypoint:
                       - "/bin/sh"
                       - "-c"
                       - "bundle install && bundle exec jekyll serve --host 0.0.0.0"
                stdin_open: true          
